### ISSUE TITLE
Slapper Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [xStrixU/PocketMine-EmoteSlapper#7]
Spawn a slapper, it looks not in the correct direction.
Step 1.. Look in a direction you want
Step 2.. Now you can see, the Slapper spawns not in this direction you look.

**Comment by MonoAdrian23** [comment]
![Screenshot_20200801-205513_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/89108514-5f944b80-d439-11ea-9d3d-afd69ae00aab.jpg)

This is the direction he should it Spawn

![Screenshot_20200801-205530_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/89108520-70dd5800-d439-11ea-9efa-f3d903e5dd08.jpg)

But it spawn evertime to right side

**Comment by twk1024** [comment]
Please make sure you are using the latest version of this plugin. That problem has been fixed already.
